TASK:
  NAME: ''
DATALOADER:
  NUM_WORKERS: 0
DATASETS:
  NAME: ''
  TRAIN: 
    PATH: ('',)
    IMG_SIZE: 0 
    BATCH_SIZE: 0
  TEST: 
    PATH: ('',)
    IMG_SIZE: 0
    BATCH_SIZE: 0
INPUT:
  NUM_CHANNELS: 0
  NORM_MEAN: []
  NORM_STD: []
OUTPUT:
  NUM_CHANNELS: 0
MODEL:
  NAME: ''
  DEVICES: []
LOSS:
  NAME: ''
SOLVER:
  NAME: ''
  NUM_EPOCHS: 0
  BASE_LR: .0
  WEIGHT_DECAY: .0
  BIAS_LR_FACTOR: .0
  BIAS_DECAY: .0
  MOMENTUM: .0
  TEST_PERIOD: 0
RECORD:
  OUTPUT_DIR: ''
  RESULT_DIR: ''
  LOG_PERIOD: 0
OPTION:
  SEED: 0
TEST:
  WEIGHT: ''
